### PR TITLE
General Improvements

### PR DESCRIPTION
**Pull request by Philipp66904**
This is a place for general improvements that might come up during future tests along with unit tests.

### CODE REVIEW

**Comment by J0hn-Lawrence** [comment]
@Philipp66904 please tag me once you want me to review

**Comment by Philipp66904** [comment]
@J0hn-Lawrence @J0las 
Please approve

**Review by J0hn-Lawrence — APPROVED** [review]
Approved

**Review by J0las — APPROVED** [review]
Looks good.
Signed off by: Johan <job8197@thi.de>

**Pull request merged**
